trigger:
  branches:
    include:
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  - group: tpfinal-vars

jobs:
  - job: BuildFront
    steps:
      - template: .azure/pipelines/templates/_build-front.yml
